import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import { Providers } from "../components/Providers";
import backGround from '../../public/background.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0, padding: 0,  boxSizing: 'border-box',position:'relative',width:'100%',height:'100%' }}>
      <Providers>
      <Image
        src={backGround}
        alt="bg"
        placeholder="blur"
        fill
        sizes="100vw"
        style={{
          objectFit: "cover",
          zIndex: -1,
        }}
      />
        {children}
      </Providers>
      </body>
    </html>
  );
}
